### PR TITLE
Upgrade moment javascript package

### PR DESCRIPTION
**Pull request by echarles**
Fixes https://github.com/jupyter/nbclassic/issues/183

### CODE REVIEW

**Comment by echarles** [comment]
Thx @RRosio

**Comment by kevin-bates** [comment]
Hello - thank you for maintaining this repo @echarles and @RRosio.

Would it be possible to get a patch release containing this commit?  The CVE is impacting some users and their ability to comfortably use nbclassic.

**Comment by kevin-bates** [comment]
Awesome Eric - thank you!

**Comment by frenzymadness** [comment]
+1 for a new release, thank you!

**Comment by echarles** [comment]
nbclassic 0.5.1 is released

**Pull request merged**
