### PR TITLE
Remove duplicate notebook_shim from setup.cfg

### PR DESCRIPTION
**Pull request by frenzymadness**

### CODE REVIEW

**Review by echarles — APPROVED** [review]
LGTM Thx @frenzymadness

**Comment by echarles** [comment]
@frenzymadness I am double checking this merged changes and see that `setup.py` has been added in the `exclude` section. Was that intended? Any unexpected impact?

**Comment by frenzymadness** [comment]
> @frenzymadness I am double checking this merged changes and see that `setup.py` has been added in the `exclude` section. Was that intended? Any unexpected impact?

setup.py was there before. The change is just a new line added at the end of the file by the web editor. See the icon at the left side of the diff.

image

**Comment by echarles** [comment]
Sound good. Thx.

**Pull request merged**
