### PR TITLE
Disable ```Test Minimum Version``` CI Job

### PR DESCRIPTION
**Pull request by echarles**
This PR bumps the minimum required version of `jupyter_client` to fit the one defined in `jupyter_server`

### CODE REVIEW

**Comment by echarles** [comment]
@blink1073 I am running this flow on my MacOs Laptop and it succeeds.

```
platform darwin -- Python 3.9.12, pytest-7.1.2, pluggy-1.0.0 -- /Users/echarles/opt/miniconda3/envs/tmp/bin/python3.9
cachedir: .pytest_cache
rootdir: /Users/echarles/datalayer/ext/jupyter-notebook-classic, configfile: pyproject.toml, testpaths: tests
plugins: anyio-3.6.1, tornasync-0.6.0.post2, nbval-0.9.6, cov-3.0.0
collected 3 items                                                                                                                                             

tests/test_notebookapp.py::test_tree_handler PASSED                                                                                                     [ 33%]
tests/test_notebookapp.py::test_notebook_handler PASSED                                                                                                 [ 66%]
tests/test_notebookapp.py::test_terminal_handler PASSED      
```

whereas it fails on the CI.

```
self = <jupyter_server.serverapp.ServerApp object at 0x7fed8b442e90>
filename = 'jupyter_config'
path = ['/home/runner/work/nbclassic/nbclassic', '/tmp/pytest-of-runner/pytest-1/test_notebook_handler0/config', '/tmp/pytest.../pytest-1/test_notebook_handler0/env/etc/jupyter', '/tmp/pytest-of-runner/pytest-1/test_notebook_handler0/etc/jupyter']
    @catch_config_error
    def load_config_file(self, filename, path=None):
        """Load config files by filename and path."""
        filename, ext = os.path.splitext(filename)
        loaded = []
        for config in self._load_config_files(filename, path=path, log=self.log,
>           raise_config_file_errors=self.raise_config_file_errors,
        ):
E       RuntimeError: generator raised StopIteration
```

**Comment by blink1073** [comment]
You tested locally with the minimum version of `jupyter_server`?

**Comment by echarles** [comment]
I have pip installed from source, which installs `jupyter-server` `1.17.0`.

**Comment by blink1073** [comment]
The version used in the min version test is [1.8](https://github.com/jupyter/nbclassic/blob/69ca14bc810b43967a703b6ef8b1286de36a29d2/setup.cfg#L31).  It looks like that needs to be bumped to a higher version.

**Comment by echarles** [comment]
I have bumped jupyter-server>=1.17.0 and get the same exception.

**Comment by blink1073** [comment]
I'm not sure then, I don't have the bandwidth to dive in on this, I'd say remove the CI job.

**Comment by echarles** [comment]
I have tried also with different python versions without luck. I will disable the job.

**Comment by echarles** [comment]
@blink1073 I have disabled the failing test in the job, and now CI is green 👌

Screenshot 2022-06-07 at 08 50 20

I have renamed this PR to `Disable...` and added a note on https://github.com/jupyter/nbclassic/issues/100#issue-1235442957

This is ready to be merged.

**Comment by blink1073** [comment]
Great, thanks!

**Pull request merged**
